---
title: "Plot and Analyze Phase 3 PREMUP"
author: "Francesco Pupillo"
date: "14/05/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Plotting data PREMUP
## A document to show example plots

### First, retrieve and reshape data

```{r, message=F}
# Pacckages needed
library(reshape2)
library(ggplot2)
library(Hmisc)

# first, source the script that extracts the performance data from the raw data
source("ComputeMemAccuracy.R")

# retrieve the file
data<-read.csv("Results Phase3.csv")

# snapshot of the first part of the dataset
print(data[1:10,])

# data is shown by scene. We need to aggregate it at the different PE levels
data$highPE<-rowMeans(data[,c(3,5,7)])
data$lowPE<-rowMeans(data[,c(2,4,6)])

print(data[1:10,7:8])

# The file is in a wide format. We need to reshape it in a long format
# select only the variables of interests
datalong<-data[,c(1, 8,9,10)]
datalong<-melt(datalong, id = "PartNum" )

# assign name "PE" to the second column
colnames(datalong)[2]<-"PE"
# assign name "Accuracy" to the third column
colnames(datalong)[3]<-"Accuracy"

# rename the PE medium level
levels(datalong$PE)[levels(datalong$PE)=="perfmediumPE"]<-"mediumPE"

# set the baseline level of PE to low
datalong$PE<-relevel(datalong$PE, ref="lowPE")

# order dataset by participant (for display purposes)
datalong<-datalong[order(datalong$PartNum),]
print(datalong[1:10,])


```

### Now the plot


```{r echo=T, message=F}
ggplot(datalong, aes(PE, Accuracy))+ geom_bar(aes(PE, Accuracy, fill = PE),
    position="dodge",stat="summary")+
stat_summary(fun.data = "mean_cl_boot", size = 0.8, geom="errorbar", width=0.2 )+ # this line adds error bars
geom_jitter( size=1,width=0.1)+  # this line adds the dots, corresponding to each participant                                                 
theme_classic()+ # changing the default theme
theme(axis.text.x = element_blank())+ # we are showing the different levels through the colors, so we can avoid naming the bars
theme(axis.ticks.x = element_blank()) # and we can remove the ticks
```

### Alternative plot, without colors
```{r echo=T, results='hide'}
ggplot(datalong, aes(PE, Accuracy))+ geom_bar(aes(PE, Accuracy),
    position="dodge",stat="summary")+
stat_summary(fun.data = "mean_cl_boot", size = 0.8, geom="errorbar", width=0.2 )+ 
geom_jitter( size=1,width=0.1)+                                                
theme_minimal()

```

### But it is a bit said, isn't it?